import { Inter } from "next/font/google";
import "./globals.css";
import { Navbar } from "./components";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body suppressHydrationWarning={true} className={inter.className}>
				<div className="max-w-[1200px] mx-auto border border-green-500 min-h-screen">
					<Navbar />
					{children}
				</div>
			</body>
		</html>
	);
}
